import type { Metadata } from "next";
import { Inter, JetBrains_Mono } from "next/font/google";
import "./globals.css";
import { EditalProvider } from "../context/EditalContext";
import { MainProvider } from "@/context/MainContext";
import { Suspense } from 'react';
import Spinner from "../components/spiner";

const geistSans = Inter({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = JetBrains_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <EditalProvider>
          <MainProvider>
            <Suspense fallback={<Spinner />}>
              {children}
            </Suspense>
          </MainProvider>
        </EditalProvider>
      </body>

    </html>
  );
}